Support for application-level caching via an lru cache with ttl
closeio/flask-ipblock pull request #6
Opened 2017-02-17 21:18 UTC by wojcikstefan

2017-02-17 22:55 UTC, thomasst requested changes

2017-02-17 22:55 UTC, thomasst commented on flask_ipblock/__init__.py
> +                if matches_ip:
`return matches_ip`

2017-02-17 22:55 UTC, thomasst commented on flask_ipblock/__init__.py
> +        self.cache = None
Can just put that in an `else` clause below (no need to double assign to `self.cache` if there's a cache)

2017-02-17 22:59 UTC, thomasst commented on flask_ipblock/__init__.py
> +        size via cache_size and the TTL (in seconds) via cache_ttl.
Clarify that size = number of IP addresses, not storage in bytes.

2017-02-18 00:18 UTC, wojcikstefan commented
@thomasst should be good now, could you take another look?

2017-02-18 00:38 UTC, thomasst approved these changes

2017-02-18 23:25 UTC, merged